### ISSUE TITLE
test.json:1:23:

### ISSUE THREAD

**Issue by ghost** [lintci/durable-json-lint-cli#2]
If a create a simple file `test.json` with the following content:

``` json
{}
```

and if I run `durable-json-lint-cli@0.0.4` on it, I get `test.json:1:23:`. It's not clear to me why and what does it mean. Could it be clarified, please?

**Comment by blatyo** [comment]
This library wraps https://github.com/freethenation/durable-json-lint, the issue is there

**Comment by ghost** [comment]
OK, thanks for the info. So, what do you suggest now? How can an end user get a working copy of your software?

**Comment by blatyo** [comment]
You should create the issue with `durable-json-lint`. This cli will work with any bugfix version released. So, if it's updated there, the cli will work the same.

**Comment by ghost** [comment]
OK, I can do that. Can you please give me any pointers regarding what is happening? I have no idea what to report.
